### ISSUE TITLE
gitflow

### ISSUE THREAD

**Issue by marcelosalloum** [stellar/java-stellar-anchor-sdk#487]
Action items from the 08-11-2022 meeting:

- [x] Create a `develop` branch: [terraform#898](https://github.com/stellar/terraform/pull/898)
- [x] Set default branch to `develop`: [terraform#898](https://github.com/stellar/terraform/pull/898)
- [x] Decide on release naming (https://semver.org/): [#515](https://github.com/stellar/java-stellar-anchor-sdk/pull/515)
- [x] Add version API endpoint, or add it to the health endpoint: [#515](https://github.com/stellar/java-stellar-anchor-sdk/pull/515)
- [x] Write release process procedure doc: [#511](https://github.com/stellar/java-stellar-anchor-sdk/pull/511)
- [x] Publish to docker: [#533](https://github.com/stellar/java-stellar-anchor-sdk/pull/533)
- [x] Publish to helm (manual step)
- [x] Publish to maven  (manual step)
- [x] Jenkinsfile change to sync kube and helm with AP feature and release branches: [pipelines#422](https://github.com/stellar/pipelines/pull/422)
- [ ] Jenkinsfile change for `release -> main` CI
- [x] Talk to ops about solving the issue around a parallel branch structure in kube and helm repos
- [x] Add version to AP config file [#497](https://github.com/stellar/java-stellar-anchor-sdk/pull/497)
  - Maybe it’s tied to the major version?

**Comment by nirojapanda** [comment]
@erika-sdf  to create a separate issue for Helm chart publish
