### ISSUE TITLE
Epic: Configuration Refactor

### ISSUE THREAD

**Issue by reecexlm** [stellar/java-stellar-anchor-sdk#490]
- [x] https://github.com/stellar/java-stellar-anchor-sdk/issues/478
- [ ] https://github.com/stellar/java-stellar-anchor-sdk/issues/339
- [x] https://github.com/stellar/java-stellar-anchor-sdk/issues/479
- [ ] https://github.com/stellar/java-stellar-anchor-sdk/issues/491
- [x] https://github.com/stellar/java-stellar-anchor-sdk/issues/480

**Comment by reecexlm** [comment]
https://docs.google.com/document/d/1rCLC9HG7hTcG9i_Se-PSk2w8ilWTRdhUOEKeehbrpvE/edit?usp=sharing
