### ISSUE TITLE
Anchor Platform Load Testing

### ISSUE THREAD

**Issue by reecexlm** [stellar/java-stellar-anchor-sdk#495]
As an Anchor Platform developer, I would like to implement a Load Test that executes the load test designed in an automated fashion (CICD).  

- [x] https://github.com/stellar/java-stellar-anchor-sdk/issues/560
- [x] https://github.com/stellar/java-stellar-anchor-sdk/issues/561
- [x] https://github.com/stellar/java-stellar-anchor-sdk/issues/562
- [x] https://github.com/stellar/java-stellar-anchor-sdk/issues/563
- [x] https://github.com/stellar/java-stellar-anchor-sdk/issues/564
- [x] https://github.com/stellar/java-stellar-anchor-sdk/issues/565
- [x] https://github.com/stellar/java-stellar-anchor-sdk/issues/566

~This story covers the tasks required to~
~- implement the load test designed in https://github.com/stellar/java-stellar-anchor-sdk/issues/488.~
~- Execute the load test and gain some preliminary results.~
~-  If possible, configure the load test within CICD against development and release branches.~
~- document and present initial findings.~
~Additional issues can be assigned for deeper load testing iterations and analysis.~
