### ISSUE TITLE
EPIC: Payment Gateway: Circle Integration

### ISSUE THREAD

**Issue by reecexlm** [stellar/java-stellar-anchor-sdk#61]
- [ ] #89
- [ ] Add a swagger documentation for the endpoints
- [ ] Add API tests
- [ ] TODO: add further sub-tasks?

**Comment by reecexlm** [comment]
removed from anchor platfrom MVP.  @marcelosalloum is this still valid to be open?
