### ISSUE TITLE
EPIC: Events

### ISSUE THREAD

**Issue by JakeUrban** [stellar/java-stellar-anchor-sdk#72]
Implement writing of Events to a queue (Kafka/SQS) in the anchor platform
Implement reading of Events from a queue (Kafka/SQS) in the anchor reference server
Deploy single instance Kafka in SDF K8s env for the anchor platform to utilize

- [x] https://github.com/stellar/java-stellar-anchor-sdk/issues/157
- [x] https://github.com/stellar/java-stellar-anchor-sdk/issues/155
- [x] https://github.com/stellar/java-stellar-anchor-sdk/issues/160
- [x] https://github.com/stellar/java-stellar-anchor-sdk/issues/193
- [x] https://github.com/stellar/java-stellar-anchor-sdk/issues/167
- [x] https://github.com/stellar/java-stellar-anchor-sdk/issues/169
- [x] https://github.com/stellar/java-stellar-anchor-sdk/issues/173
- [x] https://github.com/stellar/java-stellar-anchor-sdk/issues/175

GanttStart: 2022-02-22
GanttDue: 2022-03-12

**Comment by stfung77** [comment]
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/11511032/160699582-e58ebd9b-0a41-4598-813b-1e49ee162028.png">

https://lucid.app/lucidchart/ec619c3f-47e4-43d3-bc61-f69ba6fc8adf/edit?invitationId=inv_2d4dbdef-6f95-4582-b680-c505679ad26c
