### ISSUE TITLE
EPIC: Anchor Platform Documentation

### ISSUE THREAD

**Issue by reecexlm** [stellar/java-stellar-anchor-sdk#98]
- [x] API Docs
- [x] https://github.com/stellar/java-stellar-anchor-sdk/issues/272
- [ ] https://github.com/stellar/java-stellar-anchor-sdk/issues/227
- [x] https://github.com/stellar/java-stellar-anchor-sdk/issues/167

**Comment by reecexlm** [comment]
- [ ] API Docs
- [ ] Installation Docs
- [ ] Demo Wallet Docs
- [ ] Validation Tool Docs
- [ ] Integration Testing Docs
- [ ] Operations and Support Documentation
