### ISSUE TITLE
EPIC: Anchor Platform Deployment

### ISSUE THREAD

**Issue by reecexlm** [stellar/java-stellar-anchor-sdk#99]
Terraform, Helm, Docker, Kubernetes

- [x] https://github.com/stellar/java-stellar-anchor-sdk/issues/104
- [x] https://github.com/stellar/java-stellar-anchor-sdk/issues/83
- [x] https://github.com/stellar/java-stellar-anchor-sdk/issues/127
- [x] https://github.com/stellar/java-stellar-anchor-sdk/issues/151
- [x] https://github.com/stellar/ops/issues/1624
- [ ] https://github.com/stellar/java-stellar-anchor-sdk/issues/124
- [ ] https://github.com/stellar/java-stellar-anchor-sdk/issues/258

GanttStart: 2022-02-28
GanttDue: 2022-04-21
